/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI description (this document) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    code?: components["parameters"]["rowFilter.countries.code"];
                    name?: components["parameters"]["rowFilter.countries.name"];
                    iso2?: components["parameters"]["rowFilter.countries.iso2"];
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                    /** @description Ordering */
                    order?: components["parameters"]["order"];
                    /** @description Limiting and Pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Limiting and Pagination */
                    limit?: components["parameters"]["limit"];
                };
                header?: {
                    /** @description Limiting and Pagination */
                    Range?: components["parameters"]["range"];
                    /** @description Limiting and Pagination */
                    "Range-Unit"?: components["parameters"]["rangeUnit"];
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferCount"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["countries"][];
                        "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["countries"][];
                        "application/vnd.pgrst.object+json": components["schemas"]["countries"][];
                        "text/csv": components["schemas"]["countries"][];
                    };
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferPost"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["countries"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    code?: components["parameters"]["rowFilter.countries.code"];
                    name?: components["parameters"]["rowFilter.countries.name"];
                    iso2?: components["parameters"]["rowFilter.countries.iso2"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    code?: components["parameters"]["rowFilter.countries.code"];
                    name?: components["parameters"]["rowFilter.countries.name"];
                    iso2?: components["parameters"]["rowFilter.countries.iso2"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["countries"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/latest_ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    fideid?: components["parameters"]["rowFilter.latest_ratings.fideid"];
                    period?: components["parameters"]["rowFilter.latest_ratings.period"];
                    rating_type?: components["parameters"]["rowFilter.latest_ratings.rating_type"];
                    name?: components["parameters"]["rowFilter.latest_ratings.name"];
                    country?: components["parameters"]["rowFilter.latest_ratings.country"];
                    sex?: components["parameters"]["rowFilter.latest_ratings.sex"];
                    title?: components["parameters"]["rowFilter.latest_ratings.title"];
                    w_title?: components["parameters"]["rowFilter.latest_ratings.w_title"];
                    o_title?: components["parameters"]["rowFilter.latest_ratings.o_title"];
                    birthday?: components["parameters"]["rowFilter.latest_ratings.birthday"];
                    rating?: components["parameters"]["rowFilter.latest_ratings.rating"];
                    games?: components["parameters"]["rowFilter.latest_ratings.games"];
                    k?: components["parameters"]["rowFilter.latest_ratings.k"];
                    flag?: components["parameters"]["rowFilter.latest_ratings.flag"];
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                    /** @description Ordering */
                    order?: components["parameters"]["order"];
                    /** @description Limiting and Pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Limiting and Pagination */
                    limit?: components["parameters"]["limit"];
                };
                header?: {
                    /** @description Limiting and Pagination */
                    Range?: components["parameters"]["range"];
                    /** @description Limiting and Pagination */
                    "Range-Unit"?: components["parameters"]["rangeUnit"];
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferCount"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["latest_ratings"][];
                        "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["latest_ratings"][];
                        "application/vnd.pgrst.object+json": components["schemas"]["latest_ratings"][];
                        "text/csv": components["schemas"]["latest_ratings"][];
                    };
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    fideid?: components["parameters"]["rowFilter.ratings.fideid"];
                    period?: components["parameters"]["rowFilter.ratings.period"];
                    rating_type?: components["parameters"]["rowFilter.ratings.rating_type"];
                    name?: components["parameters"]["rowFilter.ratings.name"];
                    country?: components["parameters"]["rowFilter.ratings.country"];
                    sex?: components["parameters"]["rowFilter.ratings.sex"];
                    title?: components["parameters"]["rowFilter.ratings.title"];
                    w_title?: components["parameters"]["rowFilter.ratings.w_title"];
                    o_title?: components["parameters"]["rowFilter.ratings.o_title"];
                    birthday?: components["parameters"]["rowFilter.ratings.birthday"];
                    rating?: components["parameters"]["rowFilter.ratings.rating"];
                    games?: components["parameters"]["rowFilter.ratings.games"];
                    k?: components["parameters"]["rowFilter.ratings.k"];
                    flag?: components["parameters"]["rowFilter.ratings.flag"];
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                    /** @description Ordering */
                    order?: components["parameters"]["order"];
                    /** @description Limiting and Pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Limiting and Pagination */
                    limit?: components["parameters"]["limit"];
                };
                header?: {
                    /** @description Limiting and Pagination */
                    Range?: components["parameters"]["range"];
                    /** @description Limiting and Pagination */
                    "Range-Unit"?: components["parameters"]["rangeUnit"];
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferCount"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ratings"][];
                        "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["ratings"][];
                        "application/vnd.pgrst.object+json": components["schemas"]["ratings"][];
                        "text/csv": components["schemas"]["ratings"][];
                    };
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferPost"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["ratings"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    fideid?: components["parameters"]["rowFilter.ratings.fideid"];
                    period?: components["parameters"]["rowFilter.ratings.period"];
                    rating_type?: components["parameters"]["rowFilter.ratings.rating_type"];
                    name?: components["parameters"]["rowFilter.ratings.name"];
                    country?: components["parameters"]["rowFilter.ratings.country"];
                    sex?: components["parameters"]["rowFilter.ratings.sex"];
                    title?: components["parameters"]["rowFilter.ratings.title"];
                    w_title?: components["parameters"]["rowFilter.ratings.w_title"];
                    o_title?: components["parameters"]["rowFilter.ratings.o_title"];
                    birthday?: components["parameters"]["rowFilter.ratings.birthday"];
                    rating?: components["parameters"]["rowFilter.ratings.rating"];
                    games?: components["parameters"]["rowFilter.ratings.games"];
                    k?: components["parameters"]["rowFilter.ratings.k"];
                    flag?: components["parameters"]["rowFilter.ratings.flag"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    fideid?: components["parameters"]["rowFilter.ratings.fideid"];
                    period?: components["parameters"]["rowFilter.ratings.period"];
                    rating_type?: components["parameters"]["rowFilter.ratings.rating_type"];
                    name?: components["parameters"]["rowFilter.ratings.name"];
                    country?: components["parameters"]["rowFilter.ratings.country"];
                    sex?: components["parameters"]["rowFilter.ratings.sex"];
                    title?: components["parameters"]["rowFilter.ratings.title"];
                    w_title?: components["parameters"]["rowFilter.ratings.w_title"];
                    o_title?: components["parameters"]["rowFilter.ratings.o_title"];
                    birthday?: components["parameters"]["rowFilter.ratings.birthday"];
                    rating?: components["parameters"]["rowFilter.ratings.rating"];
                    games?: components["parameters"]["rowFilter.ratings.games"];
                    k?: components["parameters"]["rowFilter.ratings.k"];
                    flag?: components["parameters"]["rowFilter.ratings.flag"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["ratings"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/rpc/most_active_players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    p_year?: number;
                    p_country?: string;
                    p_rating_type?: string;
                    p_titles?: string;
                    p_min_age?: number;
                    p_max_age?: number;
                    p_limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferParams"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Args"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpc/rating_change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    p_year: number;
                    p_country?: string;
                    p_rating_type?: string;
                    p_titles?: string;
                    p_min_age?: number;
                    p_max_age?: number;
                    p_direction?: string;
                    p_limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferParams"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: text */
                        p_country?: string;
                        /** Format: text */
                        p_direction?: string;
                        /** Format: integer */
                        p_limit?: number;
                        /** Format: integer */
                        p_max_age?: number;
                        /** Format: integer */
                        p_min_age?: number;
                        /** Format: rating_type */
                        p_rating_type?: string;
                        /** Format: text[] */
                        p_titles?: string[];
                        /** Format: integer */
                        p_year: number;
                    };
                    "application/vnd.pgrst.object+json;nulls=stripped": {
                        /** Format: text */
                        p_country?: string;
                        /** Format: text */
                        p_direction?: string;
                        /** Format: integer */
                        p_limit?: number;
                        /** Format: integer */
                        p_max_age?: number;
                        /** Format: integer */
                        p_min_age?: number;
                        /** Format: rating_type */
                        p_rating_type?: string;
                        /** Format: text[] */
                        p_titles?: string[];
                        /** Format: integer */
                        p_year: number;
                    };
                    "application/vnd.pgrst.object+json": {
                        /** Format: text */
                        p_country?: string;
                        /** Format: text */
                        p_direction?: string;
                        /** Format: integer */
                        p_limit?: number;
                        /** Format: integer */
                        p_max_age?: number;
                        /** Format: integer */
                        p_min_age?: number;
                        /** Format: rating_type */
                        p_rating_type?: string;
                        /** Format: text[] */
                        p_titles?: string[];
                        /** Format: integer */
                        p_year: number;
                    };
                    "text/csv": {
                        /** Format: text */
                        p_country?: string;
                        /** Format: text */
                        p_direction?: string;
                        /** Format: integer */
                        p_limit?: number;
                        /** Format: integer */
                        p_max_age?: number;
                        /** Format: integer */
                        p_min_age?: number;
                        /** Format: rating_type */
                        p_rating_type?: string;
                        /** Format: text[] */
                        p_titles?: string[];
                        /** Format: integer */
                        p_year: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpc/top_players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    p_year?: number;
                    p_country?: string;
                    p_rating_type?: string;
                    p_titles?: string;
                    p_min_age?: number;
                    p_max_age?: number;
                    p_limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferParams"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Args"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        countries: {
            /**
             * Format: text
             * @description Note:
             *     This is a Primary Key.<pk/>
             */
            code: string;
            /** Format: text */
            name?: string;
            /** Format: text */
            iso2?: string;
        };
        latest_ratings: {
            /**
             * Format: integer
             * @description Note:
             *     This is a Primary Key.<pk/>
             */
            fideid?: number;
            /**
             * Format: date
             * @description Note:
             *     This is a Primary Key.<pk/>
             */
            period?: string;
            /**
             * Format: public.rating_type
             * @description Note:
             *     This is a Primary Key.<pk/>
             * @enum {string}
             */
            rating_type?: "standard" | "rapid" | "blitz";
            /** Format: text */
            name?: string;
            /** Format: text */
            country?: string;
            /** Format: text */
            sex?: string;
            /** Format: text */
            title?: string;
            /** Format: text */
            w_title?: string;
            /** Format: text */
            o_title?: string;
            /** Format: integer */
            birthday?: number;
            /** Format: integer */
            rating?: number;
            /** Format: integer */
            games?: number;
            /** Format: integer */
            k?: number;
            /** Format: text */
            flag?: string;
        };
        ratings: {
            /**
             * Format: integer
             * @description Note:
             *     This is a Primary Key.<pk/>
             */
            fideid: number;
            /**
             * Format: date
             * @description Note:
             *     This is a Primary Key.<pk/>
             */
            period: string;
            /**
             * Format: public.rating_type
             * @description Note:
             *     This is a Primary Key.<pk/>
             * @enum {string}
             */
            rating_type: "standard" | "rapid" | "blitz";
            /** Format: text */
            name: string;
            /** Format: text */
            country?: string;
            /** Format: text */
            sex?: string;
            /** Format: text */
            title?: string;
            /** Format: text */
            w_title?: string;
            /** Format: text */
            o_title?: string;
            /** Format: integer */
            birthday?: number;
            /** Format: integer */
            rating?: number;
            /** Format: integer */
            games?: number;
            /** Format: integer */
            k?: number;
            /** Format: text */
            flag?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Preference */
        preferParams: "params=single-object";
        /** @description Preference */
        preferReturn: "return=representation" | "return=minimal" | "return=none";
        /** @description Preference */
        preferCount: "count=none";
        /** @description Preference */
        preferPost: "return=representation" | "return=minimal" | "return=none" | "resolution=ignore-duplicates" | "resolution=merge-duplicates";
        /** @description Filtering Columns */
        select: string;
        /** @description On Conflict */
        on_conflict: string;
        /** @description Ordering */
        order: string;
        /** @description Limiting and Pagination */
        range: string;
        /** @description Limiting and Pagination */
        rangeUnit: string;
        /** @description Limiting and Pagination */
        offset: string;
        /** @description Limiting and Pagination */
        limit: string;
        "rowFilter.countries.code": string;
        "rowFilter.countries.name": string;
        "rowFilter.countries.iso2": string;
        "rowFilter.latest_ratings.fideid": string;
        "rowFilter.latest_ratings.period": string;
        "rowFilter.latest_ratings.rating_type": string;
        "rowFilter.latest_ratings.name": string;
        "rowFilter.latest_ratings.country": string;
        "rowFilter.latest_ratings.sex": string;
        "rowFilter.latest_ratings.title": string;
        "rowFilter.latest_ratings.w_title": string;
        "rowFilter.latest_ratings.o_title": string;
        "rowFilter.latest_ratings.birthday": string;
        "rowFilter.latest_ratings.rating": string;
        "rowFilter.latest_ratings.games": string;
        "rowFilter.latest_ratings.k": string;
        "rowFilter.latest_ratings.flag": string;
        "rowFilter.ratings.fideid": string;
        "rowFilter.ratings.period": string;
        "rowFilter.ratings.rating_type": string;
        "rowFilter.ratings.name": string;
        "rowFilter.ratings.country": string;
        "rowFilter.ratings.sex": string;
        "rowFilter.ratings.title": string;
        "rowFilter.ratings.w_title": string;
        "rowFilter.ratings.o_title": string;
        "rowFilter.ratings.birthday": string;
        "rowFilter.ratings.rating": string;
        "rowFilter.ratings.games": string;
        "rowFilter.ratings.k": string;
        "rowFilter.ratings.flag": string;
    };
    requestBodies: {
        /** @description ratings */
        ratings: {
            content: {
                "application/json": components["schemas"]["ratings"];
                "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["ratings"];
                "application/vnd.pgrst.object+json": components["schemas"]["ratings"];
                "text/csv": components["schemas"]["ratings"];
            };
        };
        Args: {
            content: {
                "application/json": {
                    /** Format: text */
                    p_country?: string;
                    /** Format: integer */
                    p_limit?: number;
                    /** Format: integer */
                    p_max_age?: number;
                    /** Format: integer */
                    p_min_age?: number;
                    /** Format: rating_type */
                    p_rating_type?: string;
                    /** Format: text[] */
                    p_titles?: string[];
                    /** Format: integer */
                    p_year?: number;
                };
                "application/vnd.pgrst.object+json;nulls=stripped": {
                    /** Format: text */
                    p_country?: string;
                    /** Format: integer */
                    p_limit?: number;
                    /** Format: integer */
                    p_max_age?: number;
                    /** Format: integer */
                    p_min_age?: number;
                    /** Format: rating_type */
                    p_rating_type?: string;
                    /** Format: text[] */
                    p_titles?: string[];
                    /** Format: integer */
                    p_year?: number;
                };
                "application/vnd.pgrst.object+json": {
                    /** Format: text */
                    p_country?: string;
                    /** Format: integer */
                    p_limit?: number;
                    /** Format: integer */
                    p_max_age?: number;
                    /** Format: integer */
                    p_min_age?: number;
                    /** Format: rating_type */
                    p_rating_type?: string;
                    /** Format: text[] */
                    p_titles?: string[];
                    /** Format: integer */
                    p_year?: number;
                };
                "text/csv": {
                    /** Format: text */
                    p_country?: string;
                    /** Format: integer */
                    p_limit?: number;
                    /** Format: integer */
                    p_max_age?: number;
                    /** Format: integer */
                    p_min_age?: number;
                    /** Format: rating_type */
                    p_rating_type?: string;
                    /** Format: text[] */
                    p_titles?: string[];
                    /** Format: integer */
                    p_year?: number;
                };
            };
        };
        /** @description countries */
        countries: {
            content: {
                "application/json": components["schemas"]["countries"];
                "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["countries"];
                "application/vnd.pgrst.object+json": components["schemas"]["countries"];
                "text/csv": components["schemas"]["countries"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
